// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnR1DIehg2I1D_-n1OXi97Wb5NBsENlJM',
    appId: '1:227455413233:web:da00a5af79722e79b03250',
    messagingSenderId: '227455413233',
    projectId: 'snacktag-app',
    authDomain: 'snacktag-app.firebaseapp.com',
    storageBucket: 'snacktag-app.firebasestorage.app',
    measurementId: 'G-981RPEMB7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcafJCZfLho2xFuKP9A3-bN8Dn2d5ar70',
    appId: '1:227455413233:android:cfc28e4ba322bef2b03250',
    messagingSenderId: '227455413233',
    projectId: 'snacktag-app',
    storageBucket: 'snacktag-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVVv-4-pZion3kd9eHGiYmhQAgepC1vgA',
    appId: '1:227455413233:ios:e234e95d45b2cbb7b03250',
    messagingSenderId: '227455413233',
    projectId: 'snacktag-app',
    storageBucket: 'snacktag-app.firebasestorage.app',
    iosBundleId: 'com.example.luncher',
  );

}